##########################################################
# DEV Profile - Finnhub configuration
##########################################################
finnhub:
  api-key: d5qkfr1r01qhn30g8uegd5qkfr1r01qhn30g8uf0
  base-url: https://finnhub.io/api/v1
